USE Cine22;
DROP USER IF EXISTS 'Administrador'@'%';
CREATE USER 'Administrador'@'%'IDENTIFIED BY 'passAdministrador';
GRANT SELECT ON Cine22.* TO 'Administrador'@'%';
DROP USER IF EXISTS 'Administrador'@'localhost';
CREATE USER 'Administrador'@'localhost'IDENTIFIED BY 'passAdministrador';
GRANT INSERT, UPDATE ON Cine22.pelicula TO 'Administrador'@'localhost';
GRANT INSERT, UPDATE ON Cine22.proyeccion TO 'Administrador'@'localhost';
GRANT INSERT, UPDATE ON Cine22.sala TO 'Administrador'@'localhost';
DROP USER IF EXISTS 'Cajero'@'10.3.45.%';
CREATE USER 'Cajero'@'10.3.45.%' IDENTIFIED BY 'passCajero';
GRANT SELECT ON Cine22.* TO 'Cajero'@'10.3.45.%';
GRANT INSERT ON Cine22.entrada TO 'Cajero'@'10.3.45.%';
DROP USER IF EXISTS 'Cliente'@'%';
CREATE USER 'Cliente'@'%' IDENTIFIED BY 'passCliente';
GRANT SELECT ON Cine22.cliente TO 'Cliente'@'%';
GRANT SELECT ON Cine22.entrada TO 'Cliente'@'%';
GRANT SELECT ON Cine22.proyeccion TO 'Cliente'@'%';
GRANT SELECT ON Cine22.pelicula TO 'Cliente'@'%';